### ISSUE TITLE
Turning Sticky notes off disables ability to apply multiple tools

### ISSUE THREAD

**Issue by AlexisRamer** [dvoegeli/webmistc#39] opened 2017-11-08 20:22 UTC
When you turn StickyNotes off using the switch, if you use a tool like pencil arrow or text box what you did only remains on the screen until you try to use another tool on the screen. I used the tools on the side with Sticky notes on and then I turned Sticky notes and drew a line using the pencil tool. Then when I clicked on the arrow tool and when I made an arrow the line I had drawn before disappeared. The same happened when I tried with any of the other drawing tools.

**Comment by dvoegeli** [comment] 2017-12-22 19:48
This is the intended behavior. Closing

**Closed as completed by dvoegeli** 2017-12-22 19:48 UTC
