### ISSUE TITLE
Inability to advance slide when in full screen

### ISSUE THREAD

**Issue by collinmcrae** [dvoegeli/webmistc#19] opened 2017-10-23 17:12 UTC
Currently, when in full screen mode the arrows to advance to the next slide disappear. If a presenter wishes to remain with the full canvas view, this requires them to exit fullscreen, advance to the next slide, and re-enter full screen view

**Comment by dvoegeli** [comment] 2017-12-06 22:28
Duplicate of #37, and fixed there also.

**Closed as completed by dvoegeli** 2017-12-06 22:28 UTC
Labels: good first issue
